---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: src/data/work.json
  label: work
- type: document
  path: src/data/fun.json
  label: fun
- type: document
  path: src/data/contact.json
  label: contact
- type: document
  path: src/data/about.json
  label: about
- type: document
  path: src/data/skills.json
  label: skills
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
